push_to_github:
  stage: deploy
  image: alpine:latest
  tags:
    - docker  # or the specific tag of your Docker runner
  before_script:
    - apk add --no-cache git git-subtree
    - git config --global user.email "hicham.laoudi@nist.gov"
    - git config --global user.name "hichamnist"
  script:
    - git fetch --unshallow || true
    - git remote add github https://x-access-token:${GITHUB_TOKEN}@github.com/usnistgov/iEdison-API-Documentation.git
    - git subtree push --prefix docs github nist-pages
  when: manual
  only:
    - main
