title: iEdison API Documentation
description: Official API documentation for iEdison system
baseurl: "/iEdison-API-Documentation"
url: "https://pages.nist.gov"

markdown: kramdown
theme: null

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
