title: iEdison API Documentation
description: Official API documentation for iEdison system
baseurl: "Edison-API-Documentation"
url: ""

markdown: kramdown
theme: null

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
